---
driver:
  name: docker
  hostname: java.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: java
  grains:
    noservices: True
  state_top:
    base:
      "*":
        - java
  pillars:
    top.sls:
      base:
        "*":
          - java

verifier:
  name: inspec
  sudo: true


platforms:
  - name: <%=ENV['PLATFORM'] || 'ubuntu-xenial'%>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'trevorj/salty-whales:xenial'%>
      platform: ubuntu

suites:

  - name: <%=ENV['JDK'] || 'openjdk'%>-<%=ENV['JAVA_VERSION'] || '8'%>
    provisioner:
      pillars-from-files:
        java.sls: tests/pillar/<%=ENV['JDK'] || 'openjdk'%>-<%=ENV['JAVA_VERSION'] || '8'%>.sls

# vim: ft=yaml sw=2 ts=2 sts=2 tw=125